/*******************************************************************************
* \file scheduler.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_reg.h"

#include "intpriodef.h"
#include "ports.h"
#include "asclin3_public.h"

volatile uint32 cnt;
volatile uint32 test;
volatile uint16 txCnt;

extern void ASCLIN3_DMA_Init(uint16 trel);

/*! \fn void scheduler(void)
 *  \brief This is simple loop for CPU0 to allow user input from a debugger.
 *  The variable "test' is used to
 *  \param None
 *  \return Nothing
 */
void scheduler(void)
{
	/* initialize ASCLIN0 to be used for UART communication using the DMA */
	ASCLIN3_Init();

	/*txCnt*/
	txCnt = 10;

	/* Enable global interrupts */
	IfxCpu_enableInterrupts();

	while (1)
	{
		if (test > 0)
		{
			/* user testing control, manipulated using a debugger */
			switch (test)
			{

				case 1:
          /* Re-initialize the transmit transfer byte count to the value = to txCnt */
				  ASCLIN3_DMA_Init(txCnt);
					break;

        case 2:
          /* Initiate the transmit transfer using the transmit FIFO level flag */
          ASCLIN3_FLAGSSET.B.TFLS = 1;
          break;

        case 3:
          /* Initiate the transmit transfer using the SRC interrupt node */
          SRC_ASCLIN3TX.U |= SETR;
          break;

				default:
					break;
			}
			test = 0;
		}

		cnt++;
	}

}


/*************************************************************************
 Development history of the file



*************************************************************************/
